config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]
  root :to => 'posts#index'

  namespace :admin do
    resources :users, only: [:index, :update]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    root :to => 'users#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categoried_post.rb
class CategoriedPost < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categoried_posts
  has_many :posts, through: :categoried_posts, dependent: :restrict_with_error
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :categoried_posts
  has_many :categories, through: :categoried_posts, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  

  def admin?
    self.role == "Admin"
  end
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin

  private
  
  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  
  def index
    @categories = Category.all
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to admin_categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to admin_categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.posts.present?
      flash[:alert] = "The category has been used"
    else
      @category.destroy
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "authority updated"
      redirect_to admin_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:role)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    @categories = Category.all
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "saved!"
      redirect_to root_path
    else
      flash.now[:alert] = @post.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :authority, :image, :category_ids => [])
  end

 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/edit.html.erb
<%= form_for [:admin, @category] do |f|%>
  <%= f.text_field :name %>
  <%= f.submit "update" %>
<% end %>

app/views/admin/categories/index.html.erb
<h1>分類後台</h1>

<%= form_for [:admin, @category] do |f|%>
  <%= f.text_field :name %>
  <%= f.submit "new" %>
<% end %>

<% @categories.each do |category|%>
  <p>
    <%= category.name%>

    <%= link_to "edit", edit_admin_category_path(category) %>
   
    <%= link_to "刪除", admin_category_path(category), method: :delete%>
  </p>
<% end %>

app/views/admin/users/index.html.erb
<h1>user後台</h1>

<% @users.each do |user| %>
  <p>
    <%= user.name %>
    <%= user.email %>
    <%= form_for [:admin, user] do |f| %>
      <%= f.select :role, options_for_select([['Normal', "Normal"],['Admin', "Admin"]], :selected => user.role) %>
      <%= f.submit "update" %>
    <% end %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DojoForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to('Dojo Forum', root_path, class: "navbar-brand") %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="pull-left text-left nav navbar-nav">
            <li><%= link_to('All Post', root_path) %></li>
            <li><%= link_to('New Post', new_post_path) %></li>
          </ul>
          <ul class="pull-right text-right nav navbar-nav">
            <% if current_user %>
              <li><%= link_to('Profile', user_path(current_user)) %></li>              
              <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
            <% else %> 
              <li><%= link_to('登入', new_user_session_path) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>文章前台</h1>

<% @posts.each do |post| %>

  <%= post.title %>
    <% post.categories.each do |c| %>
      <%= c.name %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= form_for [@post] do |f| %>
  <div class="form-group">  
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">  
    <%= f.label :content, "content" %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image, "Photo" %>
    <%= image_tag @post.image, width: '300px' if @post.image? %>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">   
    <%= f.label :authority %><br />
    <%= f.radio_button :authority, 1 %>
    <%= f.label :authority, "All", :value => "All"  %>
    <%= f.radio_button :authority, 2 %>
    <%= f.label :authority, "Friend", :value => "Friend"  %>
    <%= f.radio_button :authority, 3 %>
    <%= f.label :authority, "Myself", :value => "Myself"  %>
  </div>

  <div class="form-group">  
    <%= f.label :category %><br />
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name ) %>   
  </div>

  <div class="form-group"><br />
    <%= f.label :status, "status" %><br />
    <%= f.submit "Save Draft", name: "draft", class: "btn btn-primary right" %>
    <%= f.submit "Submit", name: "submit", class: "btn btn-primary right" %>
  </div>

  <br>
  <br>
<% end %>